/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Pharmacist } from "./Pharmacist";
import { PharmacistCountArgs } from "./PharmacistCountArgs";
import { PharmacistFindManyArgs } from "./PharmacistFindManyArgs";
import { PharmacistFindUniqueArgs } from "./PharmacistFindUniqueArgs";
import { DeletePharmacistArgs } from "./DeletePharmacistArgs";
import { PharmacistService } from "../pharmacist.service";
@graphql.Resolver(() => Pharmacist)
export class PharmacistResolverBase {
  constructor(protected readonly service: PharmacistService) {}

  async _pharmacistsMeta(
    @graphql.Args() args: PharmacistCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Pharmacist])
  async pharmacists(
    @graphql.Args() args: PharmacistFindManyArgs
  ): Promise<Pharmacist[]> {
    return this.service.pharmacists(args);
  }

  @graphql.Query(() => Pharmacist, { nullable: true })
  async pharmacist(
    @graphql.Args() args: PharmacistFindUniqueArgs
  ): Promise<Pharmacist | null> {
    const result = await this.service.pharmacist(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Pharmacist)
  async deletePharmacist(
    @graphql.Args() args: DeletePharmacistArgs
  ): Promise<Pharmacist | null> {
    try {
      return await this.service.deletePharmacist(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
