/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Medicine } from "./Medicine";
import { MedicineCountArgs } from "./MedicineCountArgs";
import { MedicineFindManyArgs } from "./MedicineFindManyArgs";
import { MedicineFindUniqueArgs } from "./MedicineFindUniqueArgs";
import { DeleteMedicineArgs } from "./DeleteMedicineArgs";
import { MedicineService } from "../medicine.service";
@graphql.Resolver(() => Medicine)
export class MedicineResolverBase {
  constructor(protected readonly service: MedicineService) {}

  async _medicinesMeta(
    @graphql.Args() args: MedicineCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Medicine])
  async medicines(
    @graphql.Args() args: MedicineFindManyArgs
  ): Promise<Medicine[]> {
    return this.service.medicines(args);
  }

  @graphql.Query(() => Medicine, { nullable: true })
  async medicine(
    @graphql.Args() args: MedicineFindUniqueArgs
  ): Promise<Medicine | null> {
    const result = await this.service.medicine(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Medicine)
  async deleteMedicine(
    @graphql.Args() args: DeleteMedicineArgs
  ): Promise<Medicine | null> {
    try {
      return await this.service.deleteMedicine(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
