/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MedicineService } from "../medicine.service";
import { MedicineCreateInput } from "./MedicineCreateInput";
import { Medicine } from "./Medicine";
import { MedicineFindManyArgs } from "./MedicineFindManyArgs";
import { MedicineWhereUniqueInput } from "./MedicineWhereUniqueInput";
import { MedicineUpdateInput } from "./MedicineUpdateInput";

export class MedicineControllerBase {
  constructor(protected readonly service: MedicineService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Medicine })
  async createMedicine(
    @common.Body() data: MedicineCreateInput
  ): Promise<Medicine> {
    return await this.service.createMedicine({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Medicine] })
  @ApiNestedQuery(MedicineFindManyArgs)
  async medicines(@common.Req() request: Request): Promise<Medicine[]> {
    const args = plainToClass(MedicineFindManyArgs, request.query);
    return this.service.medicines({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Medicine })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async medicine(
    @common.Param() params: MedicineWhereUniqueInput
  ): Promise<Medicine | null> {
    const result = await this.service.medicine({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Medicine })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateMedicine(
    @common.Param() params: MedicineWhereUniqueInput,
    @common.Body() data: MedicineUpdateInput
  ): Promise<Medicine | null> {
    try {
      return await this.service.updateMedicine({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Medicine })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteMedicine(
    @common.Param() params: MedicineWhereUniqueInput
  ): Promise<Medicine | null> {
    try {
      return await this.service.deleteMedicine({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
